project:
  type: website
output-dir: docs
website:
  title: "lmcginnis.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

# this line is just to test the github connection